"""initial_schema

Revision ID: 9afb755116c9
Revises: 
Create Date: 2026-03-09 02:38:02.967437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afb755116c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_allocations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('architect_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_allocation', sa.Float(), nullable=False),
    sa.Column('is_overloaded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('architect_name', 'date', name='uq_daily_alloc_arch_date')
    )
    op.create_index(op.f('ix_daily_allocations_architect_name'), 'daily_allocations', ['architect_name'], unique=False)
    op.create_index(op.f('ix_daily_allocations_date'), 'daily_allocations', ['date'], unique=False)
    op.create_index(op.f('ix_daily_allocations_is_overloaded'), 'daily_allocations', ['is_overloaded'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('jira_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('type_of_service', sa.String(length=255), nullable=True),
    sa.Column('practice', sa.String(length=255), nullable=True),
    sa.Column('offering_type', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=128), nullable=True),
    sa.Column('weighted_amount', sa.Float(), nullable=True),
    sa.Column('business_opportunity_type', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('market', sa.String(length=128), nullable=True),
    sa.Column('market_manager', sa.String(length=255), nullable=True),
    sa.Column('dn_manager', sa.String(length=255), nullable=False),
    sa.Column('operations_manager', sa.String(length=255), nullable=True),
    sa.Column('renewal', sa.Boolean(), nullable=True),
    sa.Column('gep_code', sa.String(length=128), nullable=True),
    sa.Column('temporal_scope', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('local_currency_budget', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('offer_code_ng', sa.String(length=255), nullable=True),
    sa.Column('offer_description_ng', sa.Text(), nullable=True),
    sa.Column('transversal', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proposal_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cloud_infra_amount', sa.Float(), nullable=True),
    sa.Column('cloud_services_amount', sa.Float(), nullable=True),
    sa.Column('cloud_service_type', sa.String(length=255), nullable=True),
    sa.Column('cloud_provider', sa.String(length=255), nullable=True),
    sa.Column('other_cloud_providers', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_jira_id'), 'offers', ['jira_id'], unique=False)
    op.create_index(op.f('ix_offers_owner'), 'offers', ['owner'], unique=False)
    op.create_index(op.f('ix_offers_practice'), 'offers', ['practice'], unique=False)
    op.create_index(op.f('ix_offers_status'), 'offers', ['status'], unique=False)
    op.create_index(op.f('ix_offers_updated_at'), 'offers', ['updated_at'], unique=False)
    op.create_table('allocation_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'PARTICIPANT', name='allocation_role'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['daily_allocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('allocation_id', 'offer_id', 'role', name='uq_alloc_detail')
    )
    op.create_index(op.f('ix_allocation_details_allocation_id'), 'allocation_details', ['allocation_id'], unique=False)
    op.create_index(op.f('ix_allocation_details_offer_id'), 'allocation_details', ['offer_id'], unique=False)
    op.create_table('offer_participants',
    sa.Column('offer_id', sa.String(length=64), nullable=False),
    sa.Column('architect_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'PARTICIPANT', name='allocation_role'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('offer_id', 'architect_name', 'role')
    )
    op.create_index(op.f('ix_offer_participants_architect_name'), 'offer_participants', ['architect_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_participants_architect_name'), table_name='offer_participants')
    op.drop_table('offer_participants')
    op.drop_index(op.f('ix_allocation_details_offer_id'), table_name='allocation_details')
    op.drop_index(op.f('ix_allocation_details_allocation_id'), table_name='allocation_details')
    op.drop_table('allocation_details')
    op.drop_index(op.f('ix_offers_updated_at'), table_name='offers')
    op.drop_index(op.f('ix_offers_status'), table_name='offers')
    op.drop_index(op.f('ix_offers_practice'), table_name='offers')
    op.drop_index(op.f('ix_offers_owner'), table_name='offers')
    op.drop_index(op.f('ix_offers_jira_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_daily_allocations_is_overloaded'), table_name='daily_allocations')
    op.drop_index(op.f('ix_daily_allocations_date'), table_name='daily_allocations')
    op.drop_index(op.f('ix_daily_allocations_architect_name'), table_name='daily_allocations')
    op.drop_table('daily_allocations')
    # ### end Alembic commands ###

